import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Inter,
  IM_Fell_Great_Primer,
} from "next/font/google";
import "../../globals.css";
import Providers from "@/app/providers";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const imFellGreatPrimer = IM_Fell_Great_Primer({
  variable: "--font-im-fell-great-primer",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${imFellGreatPrimer.variable} h-full antialiased`}
    >
      <body
        className="min-h-full flex flex-col 
      bg-linear-to-b from-[#C8DBFD] to-[#F5F8FC]"
      >
        <Providers>
            {children}
        </Providers>
      </body>
    </html>
  );
}
